const whiteKing = '<div class="piece" id="king"><img src="images/pieces/steveKing.png"></img><audio src="sounds Minecraft/steveAndAlexWalking.mp3"></audio></div>'
const whiteQueen = '<div class="piece" id="queen"><img src="images/pieces/alexQueen.jpg"></img><audio src="sounds Minecraft/steveAndAlexWalking.mp3"></audio></div>'
const whiteKnight = '<div class="piece" id="knight"><img src="images/pieces/cowKnight.png"></img><audio src="sounds Minecraft/cow01.mp3"></audio></div>'
const whiteRook = '<div class="piece" id="rook"><img src="images/pieces/sheepTower.png"></img><audio src="sounds Minecraft/sheep01.mp3"></audio></div>'
const whiteBishop = '<div class="piece" id="bishop"><img src="images/pieces/wolfBishop.png"></img><audio src="sounds Minecraft/dog01.mp3"></audio></div>'
const whitePawn = '<div class="piece" id="pawn"><img src="images/pieces/villagerPawn.png"></img><audio src="sounds Minecraft/villager01.mp3"></audio></div>'

const blackKing = '<div class="piece" id="king"><img src="images/pieces/herobrineKing.jpg"></img><audio src="sounds Minecraft/cave01.mp3"></audio></div>'
const blackQueen = '<div class="piece" id="queen"><img src="images/pieces/dragonQueen.png"></img><audio src="sounds Minecraft/dragon02.mp3"></audio></div>'
const blackKnight = '<div class="piece" id="knight"><img src="images/pieces/creeperKnight.jpg"></img><audio src="sounds Minecraft/creeper01.mp3"></audio></div>'
const blackRook = '<div class="piece" id="rook"><img src="images/pieces/endermanTower.jpg"></img><audio src="sounds Minecraft/enderman01.mp3"></audio></div>'
const blackBishop = '<div class="piece" id="bishop"><img src="images/pieces/skeletonBishop.png"></img><audio src="sounds Minecraft/skeleton01.mp3"></audio></div>'
const blackPawn = '<div class="piece" id="pawn"><img src="images/pieces/zombiePawn.png"></img><audio src="sounds Minecraft/zombie03.mp3"></audio></div>'

const blackQueenNether = '<div class="piece" id="queen"><img src="images/pieces/witherQueen.png"></img><audio src="sounds Minecraft/wither01.mp3"></audio></div>'
const blackKnightNether = '<div class="piece" id="knight"><img src="images/pieces/blazeKnight.png"></img><audio src="sounds Minecraft/blaze01.mp3"></audio></div>'
const blackRookNether = '<div class="piece" id="rook"><img src="images/pieces/ghastRook.png"></img><audio src="sounds Minecraft/ghast01.mp3"></audio></div>'
const blackBishopNether = '<div class="piece" id="bishop"><img src="images/pieces/witherSkeletonBishop.png"></img><audio src="sounds Minecraft/skeleton01.mp3"></audio></div>'
const blackPawnNether = '<div class="piece" id="pawn"><img src="images/pieces/zombiePigmanPawn.png"></img><audio src="sounds Minecraft/pigman01.mp3"></audio></div>'